<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>..\..\src\WFU.Host\bin\$(Configuration)\net8.0-windows\Plugins\BasicTheme\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WFU.PluginSDK\WFU.PluginSDK.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
